language: ruby
cache: bundler
rvm: 2.1.5

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - psql -c 'create database "hound_test";' -U postgres

services:
  - redis-server

addons:
  code_climate:
    repo_token: 'd5fa8e4ebe4bfa49f4bff04ec7df746f1ea95c983dbf84e32197302f274ce56c'